### ISSUE TITLE
Extending the Fact definition

### ISSUE THREAD

**Issue by joseph-norman** [j-easy/easy-rules#252] opened 2020-01-22 09:20 UTC
Hi,

Would you be open to the idea of extending the `Fact` definition such that it could be its own interface? I'd like to start using easy-rules but have concerns as to how Facts themselves are used. For example, I'd like to enforce immutability on incoming Facts (for my own use case).

**Comment by benas** [comment] 2020-03-02 21:09
A `Facts` object is just a bag of key/value pairs (a data carrier), I don't think we need an interface (a contract) for that, a class is more appropriate.

> I'd like to enforce immutability on incoming Facts (for my own use case).

A `Facts` object should be mutable, because rules can add/remove/modify facts and that's by design for this kind of systems. However, nothing prevents you from making your facts objects immutable. Do you agree?

**Comment by benas** [comment] 2020-03-15 23:47
Based on the previous comment, I'm closing this issue. You can add a comment here if necessary.

**Closed by benas** 2020-03-15 23:47 UTC
Labels: waiting for feedback
