### ISSUE TITLE
Adding default block to `CompositeRule`

### ISSUE THREAD

**Issue by swayamraina** [j-easy/easy-rules#218] opened 2019-07-06 15:58 UTC
As per this [SO Thread](https://stackoverflow.com/questions/54031298/easy-rules-rule-engine-can-we-fire-if-else-rule) It seems totally logical to add a `else` block if someone wants to execute a default rule iff all the rules in the chain evaluate to false.

**Comment by pallavialuri** [comment] 2019-07-16 15:43
Hi 

I am trying to implement composite rule...so heres the use case...i have main condition which checks device type and after it checks device types depending on the return value of one of the methods there are different types of actions to be implemented..could you  please provide help on how to implement..

attaching files for review.

thank you in advance
[composite rule.zip](https://github.com/j-easy/easy-rules/files/3397908/composite.rule.zip)

**Comment by zhhaojie** [comment] 2019-07-20 02:58
That’s no else in easy rules. 
Rule evaluate to true, then fire 。

**Comment by benas** [comment] 2019-09-29 12:27
@swayamraina The [answer](https://stackoverflow.com/a/58029884/5019386) to the question you mentioned on SO is what was about to write here.

This is a duplicate of issue #107 . Please check it for more details about this design choice.

@pallavialuri 

> i have main condition which checks device type and after it checks device types depending on the return value of one of the methods there are different types of actions to be implemented

the example shown in the answer mentioned previously is what you are looking for. You might need multiple rules for your use case.

**Closed by benas** 2019-09-29 12:27 UTC

**Comment by benas** [comment] 2019-09-29 12:48
Since this has been asked multiple times, I added it to the [FAQ section](https://github.com/j-easy/easy-rules/wiki/faqs#7-why-there-is-no-else-support-in-easy-rules).
