### ISSUE TITLE
Add alternative actions to rules

### ISSUE THREAD

**Issue by jokke150** [j-easy/easy-rules#107] opened 2017-08-23 18:43 UTC
I wonder if it would be a good idea to create an alternative action (else). 

The use case is, when there are different actions for the condition and its opposite.

Say *Action 1* should be executed, if *FACT* evaluates to true and *Action 2* if *FACT* evaluates to false.

With the current implementation two rules would be needed for such a scenario, if I am not mistaken.

I have seen this in IBM ODM action & technical rules. (See https://goo.gl/Ju5CzQ)

**Comment by benas** [comment] 2017-09-07 15:24
Hi @jokke150 

Thank you for opening this issue!

Easy rules works well with [production systems](https://en.wikipedia.org/wiki/Production_system_(computer_science)) (no else statement)

> With the current implementation two rules would be needed for such a scenario, if I am not mistaken.

You are not mistaken, we need to create a rule for the "if" and another one for the "else"

> I have seen this in IBM ODM action & technical rules.

Thank you for the link! I did'nt knew ODM supports this.

I don't exclude adding this feature to easy rules, but I need some time to mesure the impact on the current API (name of the annotation for the alternate action, same for the new method in the Rule interface, etc).

Any suggestion is welcome

**Comment by benas** [comment] 2017-12-06 09:59
Hey @jokke150 

For alternative actions, I was thinking of something like:

```java
@Rule(name = "weather rule", description = "if it rains then take an umbrella, else enjoy the day!" )
public class WeatherRule {

    @Condition
    public boolean itRains(@Fact("rain") boolean rain) {
        return rain;
    }
    
    @Action
    public void takeAnUmbrella() {
        System.out.println("It rains, take an umbrella!");
    }

    @Action(alternate = true)
    public void enjoyTheDay() {
        System.out.println("No rain no pain!");
    }
}
```

The engine can make the distinction between actions using the `alternate` attribute (false by default). Alternative actions are optional and can be ordered like other actions using the `order` attribute.

What do you think?

Kr,
Mahmoud

**Comment by jokke150** [comment] 2017-12-06 10:52
Hey @benas 

I almost forgot about the issue, sorry.

Your solution sounds great. With this one would not be required to create two rules with the exact opposite condition.

Thank you for your effort!

**Comment by benas** [comment] 2017-12-14 21:20
I was really thinking about this for a long time the last few days. I see a difference between ODM (which supports the else statement) and Drools (which does not support the else statement) and there is a good reason for this.

Easy Rules was designed as an implementation of a [production system](https://en.wikipedia.org/wiki/Production_system_(computer_science)) (inspired by [this article](https://martinfowler.com/bliki/RulesEngine.html)). In these systems, there is no else statement. The whole point is to be able to design the logic as condition/action and let the engine decide which rule to apply given the set of facts. I'm definitely not an expert in these systems, but I guess there is a good reason why there is no else statement *by design*.

So even though it is technically possible to implement the else statement (as shown in my previous example, or using a `otherwise` method in the `RuleBuilder` api), I would stick to the current design. 

The good thing is, one can always implement the `RulesEngine` interface and add support for else statement. But this is out of scope in Easy Rules.

Thank you for your suggestion!
I'm closing this issue for now.

**Closed by benas** 2017-12-14 21:20 UTC

**Comment by ruchichhabra009** [comment] 2018-04-18 17:00
@benas 
I am working on POC of my content-validator and want to use this rule-engine. I definitely need "else" part. could you please suggest on how can "else" be created using easy-rules. I need to generate reports based on condition evaluation status.

Thank you.

**Comment by zhhaojie** [comment] 2019-05-08 05:03
> @benas
> I am working on POC of my content-validator and want to use this rule-engine. I definitely need "else" part. could you please suggest on how can "else" be created using easy-rules. I need to generate reports based on condition evaluation status.
> 
> Thank you.

that's impossible with only a single rule in easy-rules.

`if ... then ... else ...  ` you should have to define two rules in easy-rules.
