### ISSUE TITLE
Unable to run rules having boolean conditions 

### ISSUE THREAD

**Issue by binojvr** [j-easy/easy-rules#171] opened 2018-07-24 06:03 UTC
Hi,

I have a rule condition as follows
condition : myObj. tarificable == true 
where tarificable is a boolean property within MyObj class with isTarificable() as the getter method & setTarificable () setter method.  This throws error . when I have class with  getTarificable() as the getter method & setTarificable () setter method its works fine.  unfortunately i cant the object signature as its part of common Lib. I do have work around  by changing the rule to 

condition : myObj. isTarificable() == true 

But again I am generating the rule from UI i am forced to do this only for boolean properties. 

Please find the error details

```
018-07-24 11:26:33,669 DEBUG org.jeasy.rules.mvel.MVELCondition : Unable to evaluate expression: 'ruleSupport.findObjectWithID(Garantias,114).obligatoria == true' on facts: [ { Garantias : [com.amaseguros.comunesappsws.beans.comunes.modalidad.GarantiaBean@56045d7b] } , { response : RuleResponseModel [message=null, errorCode=0, errorObjectId=0, runStatus=STARTED, errors=null] } , { ruleSupport : com.amaseguros.ruleengine.mvel.callback.DefaultRuleSupport$$EnhancerBySpringCGLIB$$11f6d447@523bd363 } ]
org.mvel2.PropertyAccessException: [Error: could not access: obligatoria; in class: com.amaseguros.comunesappsws.beans.comunes.modalidad.GarantiaBean]
[Near : {... ruleSupport.findObjectWithID(G ....}]
             ^
[Line: 1, Column: 1]
    at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.getBeanProperty(ReflectiveAccessorOptimizer.java:706)
    at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.compileGetChain(ReflectiveAccessorOptimizer.java:360)
    at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.optimizeAccessor(ReflectiveAccessorOptimizer.java:163)
    at org.mvel2.optimizers.dynamic.DynamicOptimizer.optimizeAccessor(DynamicOptimizer.java:80)
    at org.mvel2.ast.ASTNode.optimize(ASTNode.java:159)
    at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:115)
    at org.mvel2.ast.BinaryOperation.getReducedValueAccelerated(BinaryOperation.java:117)
    at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:42)
    at org.mvel2.MVEL.executeExpression(MVEL.java:968)
    at org.jeasy.rules.mvel.MVELCondition.evaluate(MVELCondition.java:59)
    at org.jeasy.rules.mvel.MVELRule.evaluate(MVELRule.java:107)
    at org.jeasy.rules.core.DefaultRulesEngine.doFire(DefaultRulesEngine.java:112)
    at org.jeasy.rules.core.DefaultRulesEngine.fire(DefaultRulesEngine.java:94)
    at com.amaseguros.ruleengine.services.RuleEngineRunnerSrv.runRules(RuleEngineRunnerSrv.java:52)
    at com.amaseguros.ruleengine.spring.controller.RuleEngineExecService.executeRules(RuleEngineExecService.java:43)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
    at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:748)
2018-07-24 11:26:33,669 INFO  org.jeasy.rules.core.DefaultRuleListener : Rule 'Name' has been evaluated to false, it has not been executed
```

**Comment by binojvr** [comment] 2018-08-02 09:59
@benas  Waiting for your suggestion

**Comment by benas** [comment] 2018-08-03 11:43
Hi, 

I need to check how MVEL introspects getters for booleans.

I'll get back to you asap (I have limited access to internet right now).

Kr,
Mahmoud

**Comment by binojvr** [comment] 2018-08-06 13:15
Thanks

**Comment by benas** [comment] 2019-02-03 23:15
I'm not able to reproduce the issue with version 2.3.0. Here is a class with a boolean field `tarificable` and a getter `isTarificable` and which is working fine with a condition of `foo.tarificable == true`:

```java
import org.jeasy.rules.api.Facts;
import org.jeasy.rules.api.Rules;
import org.jeasy.rules.api.RulesEngine;
import org.jeasy.rules.core.DefaultRulesEngine;
import org.jeasy.rules.mvel.MVELRule;

public class Foo {

    private boolean tarificable;

    public boolean isTarificable() {
        return tarificable;
    }

    public void setTarificable(boolean tarificable) {
        this.tarificable = tarificable;
    }

    public static void main(String[] args) {
        // create facts
        Facts facts = new Facts();
        Foo foo = new Foo();
        foo.setTarificable(true);
        facts.put("foo", foo);

        // create rules
        Rules rules = new Rules();
        MVELRule fooRule = new MVELRule()
                .when("foo.tarificable == true")
                .then("System.out.println(\"foo is tarificable\");");
        rules.register(fooRule);

        // create a rules engine and fire rules on known facts
        RulesEngine rulesEngine = new DefaultRulesEngine();
        rulesEngine.fire(rules, facts);
    }
}
```

prints:

```
[main] INFO org.jeasy.rules.core.DefaultRulesEngineListener - Engine parameters { skipOnFirstAppliedRule = false, skipOnFirstNonTriggeredRule = false, skipOnFirstFailedRule = false, priorityThreshold = 2147483647 }
[main] INFO org.jeasy.rules.core.DefaultRulesEngineListener - Registered rules:
[main] INFO org.jeasy.rules.core.DefaultRulesEngineListener - Rule { name = 'rule', description = 'description', priority = '2147483646'}
[main] INFO org.jeasy.rules.core.DefaultRulesEngineListener - Known facts:
[main] INFO org.jeasy.rules.core.DefaultRulesEngineListener - Fact { foo : org.jeasy.rules.tutorials.helloworld.Foo@490d6c15 }
[main] INFO org.jeasy.rules.core.DefaultRulesEngineListener - Rules evaluation started
[main] INFO org.jeasy.rules.core.DefaultRuleListener - Rule 'rule' triggered
foo is tarificable
[main] INFO org.jeasy.rules.core.DefaultRuleListener - Rule 'rule' performed successfully
```

Do you confirm?

**Comment by benas** [comment] 2019-03-17 23:38
> where tarificable is a boolean property within MyObj class with isTarificable() as the getter method & setTarificable () setter method. This throws error 

As shown in my previous comment, this works as expected with v3.2. I'm closing this issue.

**Closed by benas** 2019-03-17 23:38 UTC
Labels: waiting for feedback
