### ISSUE TITLE
Allow custom rule/rule engine listeners in AbstractRuleEngine

### ISSUE THREAD

**Issue by elitacco** [j-easy/easy-rules#215] opened 2019-06-10 10:30 UTC
After #157 there is no way to remove the default rule and rules engine listeners. It should be possible to create a rule engine with a custom list of rule listeners and rule engine listeners.

**Comment by okohub** [comment] 2019-06-11 06:50
+1 for this one.

This was a breaking change for us. We are removing default listeners when decorating DefaultRulesEngine.

**Comment by zhhaojie** [comment] 2019-07-16 07:48
> After #157 there is no way to remove the default rule and rules engine listeners. It should be possible to create a rule engine with a custom list of rule listeners and rule engine listeners.

yes, you can register your custom  list of rule listeners & rule engine listeners. but there is no way to remove the default listeners.

i wonder what's the reason you remove the defaults ?

**Comment by benas** [comment] 2019-11-05 21:50
Default listeners will be removed in next major version (See #223).

I'm closing this issue as a duplicate of #223 .

**Closed by benas** 2019-11-05 21:50 UTC
