### ISSUE TITLE
Method MVELCondition#evaluate,  I don't understand why you need to catch an exception and return false here ?

### ISSUE THREAD

**Issue by ly9622** [j-easy/easy-rules#234] opened 2019-10-18 08:27 UTC
@mahmoud.benhassine@icloud.com
MVELCondition#evaluate
 public boolean evaluate(Facts facts) {
        try {
            return (boolean) MVEL.executeExpression(compiledExpression, facts.asMap());
        } catch (Exception e) {
            LOGGER.error("Unable to evaluate expression: '" + expression + "' on facts: " + facts, e);
            return false;
        }
    }
This is easy to cause others to write a mistake and return false, Is it ok to report an exception directly?

**Comment by benas** [comment] 2019-10-27 23:15
This is a duplicate of #211 .

**Closed by benas** 2019-10-27 23:15 UTC
