### ISSUE TITLE
is there a way to add static method to YML file Condition

### ISSUE THREAD

**Issue by ruchichhabra009** [j-easy/easy-rules#162] opened 2018-05-29 18:58 UTC
Hi @benas 

Is there a way to add have something like this condition. 
Hi @benas 

I have modified the YML and it worked this way for me. But condition is not working. Could you please suggest.

```yml
validationName: "duration-validation.yml"
field: "duration"
ruleName: "duration-NullCheck"
description: "duration should not be empty"
optional: true
reason: "Missing duration"
priority: 1
condition: "RuleUtil.durationNullCheck(duration)"
actions:
  - "System.out.println(\"duration value is not available\")"
```

**Comment by benas** [comment] 2019-03-17 23:46
I'm not sure I understand your point. What do you mean by "add static method to YML file"?

**Comment by benas** [comment] 2019-03-23 00:40
@ruchichhabra009 I think I now understand your point. Is this related to #197 ? The `ParserContext` allows you to import static classes and use them in conditions. Is that what you are looking for?

Please note that #197 has been fixed so you can already try it with version `3.3.0-SNAPSHOT` (See [here](https://github.com/j-easy/easy-rules/wiki/getting-started#use-a-snapshot-version) if you don't know how to use a snapshot version).

**Comment by benas** [comment] 2019-04-08 19:34
I'm closing this issue as I believe it is a duplicate of #197.

**Closed by benas** 2019-04-08 19:34 UTC
Labels: waiting for feedback
