### ISSUE TITLE
Can ‘condition‘’ label active as array？

### ISSUE THREAD

**Issue by codeinmyself** [j-easy/easy-rules#266] opened 2020-03-24 06:43 UTC
```json
{
	"name": "1",
	"description": "print fizz if the number is multiple of 5",
	"priority": 1,
	"condition": "_context.Input.commission.commissionLevel < 1 && _context.Input.commission.phoneType == \"xxx\" ",
	"actions": [
		"_context.Input.commission.commission=1",
	]
}
```
as shown above, the condition label is composed of two expression  link with '&&',
it seems more clear and simple if we use array type like 'actions' label .

**Comment by benas** [comment] 2020-03-25 23:51
> as shown above, the condition label is composed of two expression link with '&&',
> it seems more clear and simple if we use array type like 'actions' label .

Let's try that:

```json
{
	"name": "1",
	"description": "print fizz if the number is multiple of 5",
	"priority": 1,
	"condition": [
                       "_context.Input.commission.commissionLevel < 1",
                       "_context.Input.commission.phoneType == \"xxx\""
        ],
	"actions": [
		"_context.Input.commission.commission=1",
	]
}
```

As you can see, Easy Rules would not be able to interpret if the "link" between conditions should be an "&&" or "||" or "xor", etc.

I'm closing this as a duplicate of #193 .

**Closed by benas** 2020-03-25 23:51 UTC

**Comment by codeinmyself** [comment] 2020-03-26 09:57
Thank you all the same.
In my case ,easy-rules is used to create the metadata of decision-table ,
that is why i use '&&' frequently since every decision-unit is a micro-expression.
