### ISSUE TITLE
Inconsistent SpEL expression templating between SpELRule and SpELRuleFactory

### ISSUE THREAD

**Issue by readilychen** [j-easy/easy-rules#257] opened 2020-03-10 04:17 UTC
Facts facts = new Facts();
        Person foo = new Person("foo", 20);
        facts.put("person", foo);

        SpELCondition spELCondition = new SpELCondition("person.age > 0");
        spELCondition.evaluate(facts);//got exception here

full stack as below:

```
""10 三月 2020 2020-03-10 12:13:07 [DEBUG] org.jeasy.rules.core.DefaultRulesEngine {DefaultRulesEngine.java:77} - Rules evaluation started
""10 三月 2020 2020-03-10 12:13:09 [ERROR] org.jeasy.rules.spel.SpELCondition {SpELCondition.java:83} - Unable to evaluate expression: 'person.age > 0' on facts: [ { person : Person(name=foo, age=20, isAdult=false) } ]
"org.springframework.expression.spel.SpelEvaluationException: EL1001E: Type conversion problem, cannot convert from java.lang.String to java.lang.Boolean
	at org.springframework.expression.spel.support.StandardTypeConverter.convertValue(StandardTypeConverter.java:71)
	at org.springframework.expression.common.ExpressionUtils.convertTypedValue(ExpressionUtils.java:53)
	at org.springframework.expression.common.LiteralExpression.getValue(LiteralExpression.java:88)
	at org.jeasy.rules.spel.SpELCondition.evaluate(SpELCondition.java:81)
	at org.jeasy.rules.spel.SpELRule.evaluate(SpELRule.java:130)
	at org.jeasy.rules.core.DefaultRulesEngine.doFire(DefaultRulesEngine.java:91)
	at org.jeasy.rules.core.DefaultRulesEngine.fire(DefaultRulesEngine.java:65)
	at com.iqiyi.qytrace.common.RuleTest.testRulesCreation(RuleTest.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [java.lang.Boolean] for value 'person.age > 0'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value 'person.age > 0'
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:43)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:203)
	at org.springframework.expression.spel.support.StandardTypeConverter.convertValue(StandardTypeConverter.java:67)
	... 31 more
Caused by: java.lang.IllegalArgumentException: Invalid boolean value 'person.age > 0'
	at org.springframework.core.convert.support.StringToBooleanConverter.convert(StringToBooleanConverter.java:63)
	at org.springframework.core.convert.support.StringToBooleanConverter.convert(StringToBooleanConverter.java:31)
	at org.springframework.core.convert.support.GenericConversionService$ConverterAdapter.convert(GenericConversionService.java:386)
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:37)
	... 33 more
```

**Comment by readilychen** [comment] 2020-03-10 07:51
should be :
`    SpELCondition spELCondition = new SpELCondition("#person.age > 0");
`
this goes well.


but in json file, must be started with #{['person'] as below:

[
  {
    "name": "adult rule",
    "description": "when age is greater then 18, then mark as adult",
    "priority": 1,
    "condition": "#{['person'].age > 0}",
    "actions": [
      "#{['person'].setAdult(true)}",
      "#{T(java.lang.System).out.println(['person'].age + \" years old, is adult: \" + ['person'].adult)}"
    ]
  },
  {
    "name": "weather rule",
    "description": "when it rains, then take an umbrella",
    "priority": 2,
    "condition": "#{containsKey('rain') and ['rain'] == true}",
    "actions": [
      "System.out.println(\"It rains, take an umbrella!\")"
    ]
  }
]

**Comment by readilychen** [comment] 2020-03-10 08:16
although my problem is solved, but it is very strange as we must use different rule style.

**Comment by elitacco** [comment] 2020-03-12 15:51
The problem is in [SpELRuleFactory](https://github.com/j-easy/easy-rules/blob/9fc5a8f2e284c39e74d9a499cdd7a1e09f89dd57/easy-rules-spel/src/main/java/org/jeasy/rules/spel/SpELRuleFactory.java#L62). It's creating the actions and conditions with _TemplateParserContext_ even if you don't pass any ParserContext. It should allow to create conditions and actions without ParserContext (the same way it can be done programmatically)

**Comment by snok3r** [comment] 2020-03-13 13:45
> although my problem is solved, but it is very strange as we must use different rule style.

using just `#smth` instead of `['smth']`, should work too:

```
"condition": "#{#person.age > 0}",
"actions": [
 "#{#person.setAdult(true)}"
]
```

**Comment by benas** [comment] 2020-03-20 23:40
I do confirm, there is something wrong here. The SpEL syntax should be the same wether the rule is created programmatically using the builder or from a rule descriptor using the factory. This is not the case as of v3.4. I will dig in and get back to you asap.

**Comment by benas** [comment] 2020-05-02 18:48
This is definitely a bug, as we have to use a different syntax wether we create rules using Java (`SpELRule`) or using a json/yaml file (`SpELRuleFactory`). We need to fix one of the two ways, but in both cases, this will be a breaking change.

> The problem is in SpELRuleFactory.[...]. It should allow to create conditions and actions without ParserContext (the same way it can be done programmatically)

@elitacco

Since Spring uses a template expression context by default in [bean definition](https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#expressions-beandef) and [property injection](https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#expressions-beandef-annotation-based), I decided to use that default as well here. As a Spring user, I'm used to use the syntax `#{ ... }` to resolve variables or bean references in my SpEL expressions, so I would like to "feel at home" when writing SpEL conditions/actions in Easy Rules.

So instead of making the factory create expressions **without** a template parser context by default, I made the `SpELRule` create conditions/actions **with**  a template parser context by default instead. I believe this is a better default than fixing the factory the other way around as it id consistent with Spring's default behaviour. 

@readilychen @elitacco @snok3r Does this make sense?

The change can be already tested with version 4.0.0-SNAPSHOT.

**Comment by benas** [comment] 2020-05-16 17:30
Closing this for the upcoming 4.0.0 release.

**Closed by benas** 2020-05-16 17:30 UTC
Labels: breaking change, bug

**Comment by readilychen** [comment] 2020-06-11 10:29
thanks very much

**Comment by readilychen** [comment] 2020-06-11 10:30
> Closing this for the upcoming 4.0.0 release.

thanks very much
