### ISSUE TITLE
RulesEngine  can run rules in parallel

### ISSUE THREAD

**Issue by xiaobaitany** [j-easy/easy-rules#120] opened 2017-11-15 06:38 UTC
Now, RulesEngine  runs rules one by one.  I hope the RulesEngine supports running the rules in parallel.

**Comment by benas** [comment] 2017-11-28 08:05
Hi,

Yes, this is by design. Production systems are intended to work this way in order to a rule to add/modify/remove facts so next rules can be triggered or not. If we run rules in parallel, this cannot be achieved anymore.

Does this make sense?

Kr
Mahmoud

**Comment by benas** [comment] 2017-12-11 14:22
I am closing this issue for now.

If you have any question, you can reopen it.

**Closed by benas** 2017-12-11 14:22 UTC
Labels: waiting for feedback
